const app=document.getElementById('app');
const navButtons=document.querySelectorAll('.bottom-nav button');
let audioCtx,lastFeedbackAt=0;
const APP_VERSION='0.6.0';
const BUKHARI_FILES=Array.from({length:97},(_,i)=>`data/bukhari/bukhari_${i+1}.json`);
let hadiths=[],dbReady=false,dbStatus='loading';

const ui={
ru:{dir:'ltr',brand:'Сахихайн',sub:'Сахих аль-Бухари<br>и Сахих Муслим',home:'Главная',search:'Поиск',fav:'Избранное',settings:'Настройки',hero:'Сахих аль-Бухари и Сахих Муслим в одном приложении',open:'Открыть хадисы',last:'Последний прочитанный',smart:'Умный поиск',lastH:'Последний хадис',themes:'Темы',chapters:'Разделы по книгам',back:'← Назад',searchTitle:'Поиск хадисов',searchPh:'Например: намерения, вера, намаз или номер хадиса',empty:'Ничего не найдено',favTitle:'Избранные хадисы',noFav:'Пока нет избранных хадисов',theme:'Тема',themeText:'Тёмная и светлая тема',themeBtn:'🌙 / ☀️ Переключить тему',language:'Язык приложения',languageText:'Нажмите и выберите язык интерфейса.',sound:'Звуки и отклик',soundText:'Один короткий звук и один отклик на одно касание.',soundOn:'🔇 Включить звуки',soundOff:'🔊 Выключить звуки',hapticOn:'📳 Включить отклик',hapticOff:'📴 Выключить отклик',test:'Проверить',offline:'Офлайн',offlineText:'База Бухари загружается из папки data/bukhari и готовится к офлайн-работе.',feedback:'Обратная связь',feedbackText:'Если вы нашли ошибку, у вас есть предложение или вы хотите помочь улучшить Sahihayn, свяжитесь с разработчиком.',feedbackText2:'Сообщайте об ошибках, предлагайте новые функции или делитесь своим мнением о приложении Sahihayn.',contact:'Контакт:',coming:'Скоро будет добавлено',about:'О приложении',addFav:'☆ В избранное',inFav:'★ В избранном',share:'📤 Поделиться',listen:'🎧 Слушать',print:'🖨️ Распечатать',tr:'Перевод',hadiths:'хадисов',loading:'Загрузка базы хадисов...',loaded:'База Бухари загружена',bukhari:'Сахих аль-Бухари',muslim:'Сахих Муслим',soon:'Скоро'},
ar:{dir:'rtl',brand:'الصحيحان',sub:'صحيح البخاري<br>وصحيح مسلم',home:'الرئيسية',search:'البحث',fav:'المفضلة',settings:'الإعدادات',hero:'صحيح البخاري وصحيح مسلم في تطبيق واحد',open:'فتح الأحاديث',last:'آخر حديث مقروء',smart:'بحث ذكي',lastH:'آخر حديث',themes:'السمات',chapters:'الأقسام',back:'رجوع ←',searchTitle:'البحث في الأحاديث',searchPh:'مثال: النية، الإيمان، الصلاة أو رقم الحديث',empty:'لا توجد نتائج',favTitle:'الأحاديث المفضلة',noFav:'لا توجد أحاديث مفضلة بعد',theme:'السمة',themeText:'الوضع الداكن والفاتح',themeBtn:'🌙 / ☀️ تغيير السمة',language:'لغة التطبيق',languageText:'اضغط واختر لغة الواجهة.',sound:'الصوت والاهتزاز',soundText:'صوت قصير واهتزاز واحد عند كل ضغطة.',soundOn:'🔇 تشغيل الصوت',soundOff:'🔊 إيقاف الصوت',hapticOn:'📳 تشغيل الاهتزاز',hapticOff:'📴 إيقاف الاهتزاز',test:'اختبار',offline:'بدون إنترنت',offlineText:'يتم تحميل قاعدة البخاري من مجلد data/bukhari وتجهيزها للعمل دون إنترنت.',feedback:'التواصل',feedbackText:'إذا وجدت خطأ أو لديك اقتراح أو تريد المساعدة في تحسين تطبيق Sahihayn، فتواصل مع المطور.',feedbackText2:'أرسل الأخطاء، اقترح ميزات جديدة، أو شارك رأيك حول تطبيق Sahihayn.',contact:'التواصل:',coming:'سيتم إضافته قريباً',about:'حول التطبيق',addFav:'☆ إضافة للمفضلة',inFav:'★ في المفضلة',share:'📤 مشاركة',listen:'🎧 استماع',print:'🖨️ طباعة',tr:'الترجمة',hadiths:'حديث',loading:'جاري تحميل قاعدة الأحاديث...',loaded:'تم تحميل قاعدة البخاري',bukhari:'صحيح البخاري',muslim:'صحيح مسلم',soon:'قريباً'},
ka:{dir:'ltr',brand:'საჰიჰაინი',sub:'საჰიჰ ალ-ბუხარი<br>და საჰიჰ მუსლიმი',home:'მთავარი',search:'ძებნა',fav:'რჩეულები',settings:'პარამეტრები',hero:'საჰიჰ ალ-ბუხარი და საჰიჰ მუსლიმი ერთ აპლიკაციაში',open:'ჰადისების გახსნა',last:'ბოლოს წაკითხული',smart:'ჭკვიანი ძებნა',lastH:'ბოლო ჰადისი',themes:'თემები',chapters:'წიგნების განყოფილებები',back:'← უკან',searchTitle:'ჰადისების ძებნა',searchPh:'მაგ: განზრახვა, რწმენა, ლოცვა ან ნომერი',empty:'არაფერი მოიძებნა',favTitle:'რჩეული ჰადისები',noFav:'რჩეულებში ჯერ არაფერია',theme:'თემა',themeText:'მუქი და ნათელი თემა',themeBtn:'🌙 / ☀️ თემის შეცვლა',language:'აპლიკაციის ენა',languageText:'დააჭირეთ და აირჩიეთ ინტერფეისის ენა.',sound:'ხმები და ვიბრაცია',soundText:'ერთი მოკლე ხმა და ერთი ვიბრაცია თითო შეხებაზე.',soundOn:'🔇 ხმის ჩართვა',soundOff:'🔊 ხმის გამორთვა',hapticOn:'📳 ვიბრაციის ჩართვა',hapticOff:'📴 ვიბრაციის გამორთვა',test:'შემოწმება',offline:'ოფლაინი',offlineText:'ბუხარის ბაზა იტვირთება data/bukhari საქაღალდიდან და მზადდება ოფლაინ მუშაობისთვის.',feedback:'უკუკავშირი',feedbackText:'თუ იპოვეთ შეცდომა, გაქვთ წინადადება ან გსურთ Sahihayn-ის გაუმჯობესებაში დახმარება, დაუკავშირდით დეველოპერს.',feedbackText2:'შეატყობინეთ შეცდომები, შემოგვთავაზეთ ახალი ფუნქციები ან გაგვიზიარეთ თქვენი აზრი Sahihayn-ის შესახებ.',contact:'კონტაქტი:',coming:'მალე დაემატება',about:'აპლიკაციის შესახებ',addFav:'☆ რჩეულებში დამატება',inFav:'★ რჩეულებშია',share:'📤 გაზიარება',listen:'🎧 მოსმენა',print:'🖨️ დაბეჭდვა',tr:'თარგმანი',hadiths:'ჰადისი',loading:'ჰადისების ბაზა იტვირთება...',loaded:'ბუხარის ბაზა ჩაიტვირთა',bukhari:'საჰიჰ ალ-ბუხარი',muslim:'საჰიჰ მუსლიმი',soon:'მალე'}};
const names={ru:'Русский',ar:'العربية',ka:'ქართული'};
const l=()=>pref('lang','ru');const t=k=>ui[l()][k]||ui.ru[k];const clean=s=>(s||'').replace(/\s+/g,' ').trim();
const books=[{id:'bukhari',title:{ru:'Сахих аль-Бухари',ar:'صحيح البخاري',ka:'საჰიჰ ალ-ბუხარი'},count:()=>hadiths.filter(h=>h.bookId==='bukhari').length,icon:'ب'},{id:'muslim',title:{ru:'Сахих Муслим',ar:'صحيح مسلم',ka:'საჰიჰ მუსლიმი'},count:()=>0,icon:'م',soon:true}];
const txt=o=>o?.[l()]||o?.ru||o||'';
let state={page:'home',query:'',book:'bukhari'};
function pref(k,f='on'){return localStorage.getItem('sahihayn:'+k)||f}function setPref(k,v){localStorage.setItem('sahihayn:'+k,v)}
function getFavorites(){return JSON.parse(localStorage.getItem('sahihayn:favorites')||'[]')}function setFavorites(x){localStorage.setItem('sahihayn:favorites',JSON.stringify(x))}function isFav(id){return getFavorites().includes(id)}function saveLast(id){localStorage.setItem('sahihayn:last',id)}
function parseNumber(reference){let m=(reference||'').match(/Sahih al-Bukhari\s+(\d+)/i);return m?Number(m[1]):0}
function parseBook(reference){let m=(reference||'').match(/Book\s+(\d+),\s*Hadith\s+(\d+)/i);return {book:m?Number(m[1]):0,inBook:m?Number(m[2]):0}}
async function loadBukhari(){dbStatus='loading';render();let loaded=[];for(const file of BUKHARI_FILES){try{let r=await fetch(file+'?v=060');if(!r.ok)continue;let arr=await r.json();let bookNo=Number((file.match(/bukhari_(\d+)/)||[])[1]||0);arr.forEach((x,i)=>{let n=parseNumber(x.reference)||((bookNo*10000)+i+1);let b=parseBook(x.reference);loaded.push({id:`bukhari-${n}`,bookId:'bukhari',number:n,bookNo:b.book||bookNo,inBook:b.inBook||i+1,chapterId:`book-${b.book||bookNo}`,title:{ru:`Хадис ${n}`,ar:`حديث ${n}`,ka:`ჰადისი ${n}`},book:{ru:`Книга ${b.book||bookNo}`,ar:`كتاب ${b.book||bookNo}`,ka:`წიგნი ${b.book||bookNo}`},arabic:x.arabic||'',tr:{ru:x.english||'',ar:x.english||'',ka:x.english||''},english:x.english||'',reference:x.reference||''})})}catch(e){}}
hadiths=loaded.sort((a,b)=>a.number-b.number);dbReady=hadiths.length>0;dbStatus=dbReady?'loaded':'error';render()}
function applyLang(){document.documentElement.lang=l();document.documentElement.dir=ui[l()].dir;document.querySelector('.brand h1').textContent=t('brand');document.querySelector('.brand p').innerHTML=t('sub');navButtons[0].querySelector('span').textContent=t('home');navButtons[1].querySelector('span').textContent=t('search');navButtons[2].querySelector('span').textContent=t('fav');navButtons[3].querySelector('span').textContent=t('settings')}
function tapSound(k='tap'){if(pref('sounds')==='off')return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.frequency.value=k==='ok'?920:620;g.gain.setValueAtTime(.001,n);g.gain.exponentialRampToValueAtTime(.055,n+.01);g.gain.exponentialRampToValueAtTime(.001,n+.07);o.connect(g);g.connect(audioCtx.destination);o.start(n);o.stop(n+.075)}catch(e){}}
function tapFeel(k='tap'){let n=Date.now();if(n-lastFeedbackAt<140)return;lastFeedbackAt=n;if(pref('haptic')!=='off'&&navigator.vibrate)navigator.vibrate(28);tapSound(k)}
function setPage(p){state.page=p;navButtons.forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}function render(){applyLang();if(state.page==='home')renderHome();if(state.page==='search')renderSearch();if(state.page==='favorites')renderFavorites();if(state.page==='settings')renderSettings()}
function renderHome(){let last=hadiths.find(h=>h.id===localStorage.getItem('sahihayn:last'));app.innerHTML=`<section class="screen"><div class="hero-card"><div class="calligraphy">صحيح</div><h2>${t('brand')}</h2><p>${dbStatus==='loading'?t('loading'):t('loaded')}: ${hadiths.length} ${t('hadiths')}</p></div><div class="books">${books.map(b=>`<article class="book-card" onclick="tapFeel();${b.soon?'alert(t(\'soon\'))':`openBook('${b.id}')`}"><div class="book-icon">${b.icon}</div><div><h3>${txt(b.title)}</h3><p class="muted">${b.soon?t('soon'):(b.count())+' '+t('hadiths')}</p></div><button class="gold-btn">${b.soon?t('soon'):t('open')}</button></article>`).join('')}</div>${last?`<h3>${t('last')}</h3>${hadithItem(last)}`:''}<div class="features"><div class="feature">🔍 ${t('smart')}</div><div class="feature">⭐ ${t('fav')}</div><div class="feature">🔖 ${t('lastH')}</div><div class="feature">🌙 ${t('themes')}</div></div></section>`}
function openBook(id){state.book=id;let groups=[...new Set(hadiths.filter(h=>h.bookId===id).map(h=>h.bookNo))].sort((a,b)=>a-b);app.innerHTML=`<section class="screen"><button class="small-btn" onclick="renderHome()">${t('back')}</button><h2>${t('bukhari')}</h2><p class="muted">${hadiths.length} ${t('hadiths')}</p><div class="chapter-list">${groups.map(g=>`<article class="chapter-card" onclick="tapFeel();openChapter(${g})"><span>${t('chapters')} ${g}</span><span>›</span></article>`).join('')}</div></section>`}
function openChapter(bookNo){let list=hadiths.filter(h=>h.bookNo===bookNo);app.innerHTML=`<section class="screen"><button class="small-btn" onclick="openBook('bukhari')">${t('back')}</button><h2>${t('bukhari')}</h2><p class="muted">${t('chapters')} ${bookNo} · ${list.length} ${t('hadiths')}</p><div class="chapter-list">${list.map(hadithItem).join('')}</div></section>`}
function hadithItem(h){return`<article class="hadith-card" onclick="tapFeel();renderHadith('${h.id}')"><b>${t('bukhari')} ${h.number}</b><p>${txt(h.title)}</p><p class="muted">${clean(h.english).slice(0,120)}...</p></article>`}
function renderHadith(id){let h=hadiths.find(x=>x.id===id);if(!h)return;saveLast(id);app.innerHTML=`<section class="screen"><button class="small-btn" onclick="render()">${t('back')}</button><h2>${t('bukhari')} ${h.number}</h2><p class="muted">${h.reference}</p><article class="hadith-card print-area"><h3>${txt(h.title)}</h3><div class="arabic">${h.arabic}</div><hr><p><b>English</b></p><p class="translation">${h.english}</p><div class="print-watermark">Sahihayn · ${t('bukhari')}</div><div class="actions"><button class="small-btn" onclick="toggleFav('${h.id}')">${isFav(h.id)?t('inFav'):t('addFav')}</button><button class="small-btn" onclick="shareHadith('${h.id}')">${t('share')}</button><button class="small-btn" onclick="speakHadith('${h.id}')">${t('listen')}</button><button class="small-btn" onclick="printHadith()">${t('print')}</button></div></article></section>`}
function toggleFav(id){let f=getFavorites();setFavorites(f.includes(id)?f.filter(x=>x!==id):[...f,id]);renderHadith(id)}
function renderSearch(){let q=state.query.toLowerCase().trim();let r=hadiths.filter(h=>!q||String(h.number)===q||`${h.reference} ${h.arabic} ${h.english}`.toLowerCase().includes(q)).slice(0,80);app.innerHTML=`<section class="screen"><h2>${t('searchTitle')}</h2><input class="search-input" placeholder="${t('searchPh')}" value="${state.query}" oninput="state.query=this.value;renderSearch()"><div class="chapter-list">${dbStatus==='loading'?`<p class="empty">${t('loading')}</p>`:(r.map(hadithItem).join('')||`<p class="empty">${t('empty')}</p>`)}</div></section>`}
function renderFavorites(){let list=hadiths.filter(h=>getFavorites().includes(h.id));app.innerHTML=`<section class="screen"><h2>${t('favTitle')}</h2><div class="chapter-list">${list.map(hadithItem).join('')||`<p class="empty">${t('noFav')}</p>`}</div></section>`}
function renderSettings(){app.innerHTML=`<section class="screen"><h2>${t('settings')}</h2><article class="setting-card"><h3>${t('language')}</h3><p class="muted">${t('languageText')}</p><select class="language-select" onchange="setLang(this.value)"><option value="ru" ${l()==='ru'?'selected':''}>Русский</option><option value="ar" ${l()==='ar'?'selected':''}>العربية</option><option value="ka" ${l()==='ka'?'selected':''}>ქართული</option></select></article><article class="setting-card"><h3>${t('theme')}</h3><p class="muted">${t('themeText')}</p><button class="gold-btn" onclick="toggleTheme()">${t('themeBtn')}</button></article><article class="setting-card"><h3>${t('sound')}</h3><p class="muted">${t('soundText')}</p><button class="gold-btn" onclick="toggleSounds()">${pref('sounds')==='off'?t('soundOn'):t('soundOff')}</button><br><br><button class="gold-btn" onclick="toggleHaptic()">${pref('haptic')==='off'?t('hapticOn'):t('hapticOff')}</button><br><br><button class="small-btn" onclick="tapFeel('ok')">${t('test')}</button></article><article class="setting-card"><h3>${t('offline')}</h3><p class="muted">${t('offlineText')}</p><p>${dbStatus==='loading'?t('loading'):t('loaded')}: ${hadiths.length}</p></article><article class="setting-card"><h3>${t('feedback')}</h3><p>${t('feedbackText')}</p><p class="muted">${t('feedbackText2')}</p><p><b>${t('contact')}</b><br>${t('coming')}</p></article><article class="setting-card" style="text-align:center"><h3>${t('about')}</h3><h2>Sahihayn</h2><p class="muted">Version ${APP_VERSION}</p><p>© 2026 Adam Margoev<br>All Rights Reserved</p></article></section>`}
function setLang(x){setPref('lang',x);tapFeel('ok');render()}function toggleTheme(){document.body.classList.toggle('light');setPref('theme',document.body.classList.contains('light')?'light':'dark')}function toggleSounds(){setPref('sounds',pref('sounds')==='off'?'on':'off');renderSettings()}function toggleHaptic(){setPref('haptic',pref('haptic')==='off'?'on':'off');renderSettings()}function printHadith(){tapFeel('ok');window.print()}
function shareHadith(id){let h=hadiths.find(x=>x.id===id),text=`${t('bukhari')} ${h.number}\n\n${clean(h.english)}\n\n${clean(h.arabic)}`;if(navigator.share)navigator.share({title:`${t('bukhari')} ${h.number}`,text});else navigator.clipboard.writeText(text).then(()=>alert('Copied'))}function speakHadith(id){let h=hadiths.find(x=>x.id===id);speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(h.english))}
navButtons.forEach(btn=>btn.addEventListener('click',()=>setPage(btn.dataset.page)));document.getElementById('searchBtn').addEventListener('click',()=>setPage('search'));document.addEventListener('click',e=>{if(e.target.closest('button'))tapFeel()},{capture:true});if(pref('theme','dark')==='light')document.body.classList.add('light');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();loadBukhari();
