const app=document.getElementById('app');
const navButtons=document.querySelectorAll('.bottom-nav button');
let audioCtx,lastFeedbackAt=0;
const APP_VERSION='0.6.2';
const BUKHARI_FILES=Array.from({length:97},(_,i)=>`data/bukhari/bukhari_${i+1}.json`);
const MUSLIM_FILES=[
'001_the_book_of_faith.json','002_the_book_of_purification.json','003_the_book_of_menstruation.json','004_the_book_of_prayers.json','005_the_book_of_mosques_and_places_of_prayer.json','006_the_book_of_prayer_-_travellers.json','007_the_book_of_prayer_-_friday.json','008_the_book_of_prayer_-_two_eids.json','009_the_book_of_prayer_-_rain.json','010_the_book_of_prayer_-_eclipses.json','011_the_book_of_prayer_-_funerals.json','012_the_book_of_zakat.json','013_the_book_of_fasting.json','014_the_book_of_itikaf.json','015_the_book_of_pilgrimage.json','016_the_book_of_marriage.json','017_the_book_of_suckling.json','018_the_book_of_divorce.json','019_the_book_of_invoking_curses.json','020_the_book_of_emancipating_slaves.json','021_the_book_of_transactions.json','022_the_book_of_musaqah.json','023_the_book_of_the_rules_of_inheritance.json','024_the_book_of_gifts.json','025_the_book_of_wills.json','026_the_book_of_vows.json','027_the_book_of_oaths.json','028_the_book_of_oaths_muharibin_qasas_retaliation_and_diyat_blood_money.json','029_the_book_of_legal_punishments.json','030_the_book_of_judicial_decisions.json','031_the_book_of_lost_property.json','032_the_book_of_jihad_and_expeditions.json','033_the_book_on_government.json','034_the_book_of_hunting_slaughter_and_what_may_be_eaten.json','035_the_book_of_sacrifices.json','036_the_book_of_drinks.json','037_the_book_of_clothes_and_adornment.json','038_the_book_of_manners_and_etiquette.json','039_the_book_of_greetings.json','040_the_book_concerning_the_use_of_correct_words.json','041_the_book_of_poetry.json','042_the_book_of_dreams.json','043_the_book_of_virtues.json','044_the_book_of_the_merits_of_the_companions.json','045_the_book_of_virtue_enjoining_good_manners_and_joining_of_the_ties_of_kinship.json','046_the_book_of_destiny.json','047_the_book_of_knowledge.json','048_the_book_pertaining_to_the_remembrance_of_allah_supplication_repentance_and_seeking_forgiveness.json','049_the_book_of_heart_melting_traditions.json','050_the_book_of_repentance.json','051_characteristics_of_the_hypocrites_and_rulings_concerning_them.json','052_characteristics_of_the_day_of_judgment_paradise_and_hell.json','053_the_book_of_paradise_its_description_its_bounties_and_its_inhabitants.json','054_the_book_of_tribulations_and_portents_of_the_last_hour.json','055_the_book_of_zuhd_and_softening_of_hearts.json','056_the_book_of_commentary_on_the_quran.json'
].map(x=>`data/muslim/${x}`);
let hadiths=[],dbStatus='loading';
const ui={ru:{dir:'ltr',home:'Главная',search:'Поиск',fav:'Избранное',settings:'Настройки',open:'Открыть',back:'← Назад',searchTitle:'Поиск хадисов',searchPh:'Номер, слово, книга...',empty:'Ничего не найдено',favTitle:'Избранные хадисы',noFav:'Пока нет избранных',theme:'Тема',themeBtn:'🌙 / ☀️ Переключить тему',language:'Язык приложения',offline:'База хадисов',loading:'Загрузка базы хадисов...',loaded:'База загружена',bukhari:'Sahih al-Bukhari',muslim:'Sahih Muslim',hadiths:'хадисов',books:'Книги',translation:'Перевод',englishSource:'Пока нет русского перевода. Временно показан английский перевод из базы.',addFav:'☆ В избранное',inFav:'★ В избранном',share:'📤 Поделиться',listen:'🎧 Слушать',print:'🖨️ Печать',about:'О приложении',sound:'Звуки и отклик',test:'Проверить'},en:{dir:'ltr',home:'Home',search:'Search',fav:'Favorites',settings:'Settings',open:'Open',back:'← Back',searchTitle:'Hadith Search',searchPh:'Number, word, book...',empty:'Nothing found',favTitle:'Favorite Hadiths',noFav:'No favorites yet',theme:'Theme',themeBtn:'🌙 / ☀️ Toggle theme',language:'App language',offline:'Hadith database',loading:'Loading hadith database...',loaded:'Database loaded',bukhari:'Sahih al-Bukhari',muslim:'Sahih Muslim',hadiths:'hadiths',books:'Books',translation:'Translation',englishSource:'English translation from database.',addFav:'☆ Favorite',inFav:'★ Favorited',share:'📤 Share',listen:'🎧 Listen',print:'🖨️ Print',about:'About',sound:'Sounds and feedback',test:'Test'},ka:{dir:'ltr',home:'მთავარი',search:'ძებნა',fav:'რჩეულები',settings:'პარამეტრები',open:'გახსნა',back:'← უკან',searchTitle:'ჰადისების ძებნა',searchPh:'ნომერი, სიტყვა, წიგნი...',empty:'არაფერი მოიძებნა',favTitle:'რჩეული ჰადისები',noFav:'რჩეულებში ჯერ არაფერია',theme:'თემა',themeBtn:'🌙 / ☀️ თემის შეცვლა',language:'აპლიკაციის ენა',offline:'ჰადისების ბაზა',loading:'ჰადისების ბაზა იტვირთება...',loaded:'ბაზა ჩაიტვირთა',bukhari:'Sahih al-Bukhari',muslim:'Sahih Muslim',hadiths:'ჰადისი',books:'წიგნები',translation:'თარგმანი',englishSource:'ქართული თარგმანი ჯერ არ არის დამატებული. დროებით ნაჩვენებია ინგლისური თარგმანი ბაზიდან.',addFav:'☆ რჩეულებში',inFav:'★ რჩეულებშია',share:'📤 გაზიარება',listen:'🎧 მოსმენა',print:'🖨️ ბეჭდვა',about:'აპლიკაციის შესახებ',sound:'ხმები და ვიბრაცია',test:'შემოწმება'}};
const l=()=>localStorage.getItem('sahihayn:lang')||'ru';const t=k=>(ui[l()]||ui.ru)[k]||ui.ru[k]||k;const clean=s=>(s||'').replace(/\s+/g,' ').trim();
let state={page:'home',query:'',book:null};
function favs(){return JSON.parse(localStorage.getItem('sahihayn:favorites')||'[]')}function saveFavs(x){localStorage.setItem('sahihayn:favorites',JSON.stringify(x))}function isFav(id){return favs().includes(id)}
function parseBukhariNumber(ref){let m=(ref||'').match(/Sahih al-Bukhari\s+(\d+)/i);return m?m[1]:''}function parseBukhariBook(ref){let m=(ref||'').match(/Book\s+(\d+),\s*Hadith\s+(\d+)/i);return {book:m?+m[1]:0,inBook:m?+m[2]:0}}
function translateOf(h){let lang=l();if(lang==='en')return {text:h.english||'',note:t('englishSource')};let direct=lang==='ru'?(h.ru||h.russian):(h.ka||h.georgian);return direct?{text:direct,note:''}:{text:h.english||'',note:t('englishSource')}}
async function loadJson(file){try{let r=await fetch(file+'?v=062');if(!r.ok)return [];let j=await r.json();return Array.isArray(j)?j:(Array.isArray(j.hadiths)?j.hadiths:[])}catch(e){return []}}
async function loadData(){dbStatus='loading';render();let all=[];for(const file of BUKHARI_FILES){let arr=await loadJson(file);let fileNo=+(file.match(/bukhari_(\d+)/)||[])[1]||0;arr.forEach((x,i)=>{let num=parseBukhariNumber(x.reference)||`${fileNo}-${i+1}`;let b=parseBukhariBook(x.reference);all.push({id:`bukhari-${num}`,collection:'bukhari',number:num,bookNo:b.book||fileNo,inBook:b.inBook||i+1,bookTitle:`Book ${b.book||fileNo}`,reference:x.reference||`Sahih al-Bukhari ${num}`,arabic:x.arabic||'',english:x.english||'',ru:x.ru||x.russian,ka:x.ka||x.georgian})})}
for(const file of MUSLIM_FILES){let arr=await loadJson(file);arr.forEach((x,i)=>{let ref=x.reference||x.grade||'';let num=(ref.match(/Sahih Muslim\s+([^\s]+)/i)||[])[1]||x.id||`${i+1}`;all.push({id:`muslim-${num}-${i}`,collection:'muslim',number:num,bookNo:+(file.match(/(\d+)_/)||[])[1]||0,inBook:x.id||i+1,bookTitle:x.book||file.split('/').pop().replace('.json','').replace(/^\d+_/,'').replaceAll('_',' '),reference:ref||`Sahih Muslim ${num}`,arabic:x.arabic||'',english:x.english||'',ru:x.ru||x.russian,ka:x.ka||x.georgian})})}
hadiths=all;dbStatus='loaded';render()}
function applyLang(){document.documentElement.lang=l();document.documentElement.dir=(ui[l()]||ui.ru).dir;let h=document.querySelector('.brand h1'),p=document.querySelector('.brand p');if(h)h.textContent='Sahihayn';if(p)p.innerHTML='Sahih al-Bukhari<br>Sahih Muslim';navButtons[0].querySelector('span').textContent=t('home');navButtons[1].querySelector('span').textContent=t('search');navButtons[2].querySelector('span').textContent=t('fav');navButtons[3].querySelector('span').textContent=t('settings')}
function tap(){let n=Date.now();if(n-lastFeedbackAt<140)return;lastFeedbackAt=n;if(localStorage.getItem('sahihayn:haptic')!=='off'&&navigator.vibrate)navigator.vibrate(25)}
function setPage(p){state.page=p;navButtons.forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
function bookCount(c){return hadiths.filter(h=>h.collection===c).length}function bookName(c){return c==='bukhari'?t('bukhari'):t('muslim')}
function render(){applyLang();if(state.page==='home')home();if(state.page==='search')search();if(state.page==='favorites')favorites();if(state.page==='settings')settings()}
function home(){app.innerHTML=`<section class="screen"><div class="hero-card"><div class="calligraphy">صحيح</div><h2>Sahihayn</h2><p>${dbStatus==='loading'?t('loading'):t('loaded')}: ${hadiths.length} ${t('hadiths')}</p></div><div class="books"><article class="book-card" onclick="openBook('bukhari')"><div class="book-icon">ب</div><div><h3>${t('bukhari')}</h3><p class="muted">${bookCount('bukhari')} ${t('hadiths')}</p></div><button class="gold-btn">${t('open')}</button></article><article class="book-card" onclick="openBook('muslim')"><div class="book-icon">م</div><div><h3>${t('muslim')}</h3><p class="muted">${bookCount('muslim')} ${t('hadiths')}</p></div><button class="gold-btn">${t('open')}</button></article></div></section>`}
function openBook(c){state.book=c;let groups=[...new Map(hadiths.filter(h=>h.collection===c).map(h=>[h.bookNo, h.bookTitle])).entries()].sort((a,b)=>a[0]-b[0]);app.innerHTML=`<section class="screen"><button class="small-btn" onclick="home()">${t('back')}</button><h2>${bookName(c)}</h2><p class="muted">${bookCount(c)} ${t('hadiths')}</p><div class="chapter-list">${groups.map(([n,title])=>`<article class="chapter-card" onclick="openChapter('${c}',${n})"><span>${n}. ${title}</span><span>›</span></article>`).join('')}</div></section>`}
function openChapter(c,n){let list=hadiths.filter(h=>h.collection===c&&h.bookNo===n);app.innerHTML=`<section class="screen"><button class="small-btn" onclick="openBook('${c}')">${t('back')}</button><h2>${bookName(c)}</h2><p class="muted">${list[0]?.bookTitle||''}</p><div class="chapter-list">${list.map(item).join('')}</div></section>`}
function item(h){let tr=translateOf(h).text;return`<article class="hadith-card" onclick="renderHadith('${h.id}')"><b>${bookName(h.collection)} ${h.number}</b><p class="muted">${clean(tr).slice(0,150)}...</p></article>`}
function renderHadith(id){let h=hadiths.find(x=>x.id===id);if(!h)return;localStorage.setItem('sahihayn:last',id);let tr=translateOf(h);app.innerHTML=`<section class="screen"><button class="small-btn" onclick="render()">${t('back')}</button><h2>${bookName(h.collection)} ${h.number}</h2><p class="muted">${h.reference}</p><article class="hadith-card print-area"><div class="arabic">${h.arabic}</div><hr><p><b>${t('translation')}</b></p><p class="translation">${tr.text}</p>${tr.note?`<p class="muted">${tr.note}</p>`:''}<div class="actions"><button class="small-btn" onclick="toggleFav('${h.id}')">${isFav(h.id)?t('inFav'):t('addFav')}</button><button class="small-btn" onclick="shareHadith('${h.id}')">${t('share')}</button><button class="small-btn" onclick="speakHadith('${h.id}')">${t('listen')}</button><button class="small-btn" onclick="window.print()">${t('print')}</button></div></article></section>`}
function toggleFav(id){let f=favs();saveFavs(f.includes(id)?f.filter(x=>x!==id):[...f,id]);renderHadith(id)}
function search(){let q=state.query.toLowerCase().trim();let r=hadiths.filter(h=>!q||`${h.number} ${h.reference} ${h.bookTitle} ${h.arabic} ${h.english}`.toLowerCase().includes(q)).slice(0,120);app.innerHTML=`<section class="screen"><h2>${t('searchTitle')}</h2><input class="search-input" placeholder="${t('searchPh')}" value="${state.query}" oninput="state.query=this.value;search()"><div class="chapter-list">${dbStatus==='loading'?`<p class="empty">${t('loading')}</p>`:(r.map(item).join('')||`<p class="empty">${t('empty')}</p>`)}</div></section>`}
function favorites(){let list=hadiths.filter(h=>favs().includes(h.id));app.innerHTML=`<section class="screen"><h2>${t('favTitle')}</h2><div class="chapter-list">${list.map(item).join('')||`<p class="empty">${t('noFav')}</p>`}</div></section>`}
function settings(){app.innerHTML=`<section class="screen"><h2>${t('settings')}</h2><article class="setting-card"><h3>${t('language')}</h3><select class="language-select" onchange="localStorage.setItem('sahihayn:lang',this.value);render()"><option value="ru" ${l()==='ru'?'selected':''}>Русский</option><option value="en" ${l()==='en'?'selected':''}>English</option><option value="ka" ${l()==='ka'?'selected':''}>ქართული</option></select></article><article class="setting-card"><h3>${t('theme')}</h3><button class="gold-btn" onclick="document.body.classList.toggle('light')">${t('themeBtn')}</button></article><article class="setting-card"><h3>${t('offline')}</h3><p>${dbStatus==='loading'?t('loading'):t('loaded')}: ${hadiths.length}</p><p>${t('bukhari')}: ${bookCount('bukhari')}</p><p>${t('muslim')}: ${bookCount('muslim')}</p></article><article class="setting-card" style="text-align:center"><h3>${t('about')}</h3><h2>Sahihayn</h2><p class="muted">Version ${APP_VERSION}</p><p>© 2026 Adam Margoev<br>All Rights Reserved</p></article></section>`}
function shareHadith(id){let h=hadiths.find(x=>x.id===id),tr=translateOf(h).text,text=`${bookName(h.collection)} ${h.number}\n${h.reference}\n\n${h.arabic}\n\n${tr}`;if(navigator.share)navigator.share({title:`${bookName(h.collection)} ${h.number}`,text});else navigator.clipboard.writeText(text)}function speakHadith(id){let h=hadiths.find(x=>x.id===id);speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(translateOf(h).text))}
navButtons.forEach(btn=>btn.addEventListener('click',()=>setPage(btn.dataset.page)));document.getElementById('searchBtn').addEventListener('click',()=>setPage('search'));document.addEventListener('click',e=>{if(e.target.closest('button'))tap()},{capture:true});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();loadData();
